/**
 * [Quant System - The Reporter] Phase 3: AI Reporting & Alerting
 * - Role: Read processed signals and raw data from Supabase, run Gemini AI analysis, and send daily emails.
 * - This script is meant to be run daily AFTER the Python Engine has finished its analysis.
 */

const CONFIG = {
  // [1] Supabase
  SB_URL: 'https://fcuenflxkkpyplehsizg.supabase.co',
  SB_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjdWVuZmx4a2tweXBsZWhzaXpnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTUxNTk2OCwiZXhwIjoyMDg1MDkxOTY4fQ.Ic-Hc8j67bkYsUKTmcbwh5RwjI84PNS6W75lkW_bnEs',

  // [2] Gemini AI
  GEMINI_API_KEY: 'AIzaSyA6OXyOp50TAIr4SskaCV3Kzal9mQmP5qg',

  // [3] Email Settings
  EMAIL_RECIPIENT: "ahnjhyung1234@gmail.com, ahnraphael1234@gmail.com"
};

// ==========================================
// [MAIN FUNCTION] Triggered after Python execution
// ==========================================
function runDailyReporter() {
  console.log("--- 📢 [Reporter] Starting AI Briefing ---");
  const todayKR = Utilities.formatDate(new Date(), "Asia/Seoul", "yyyy-MM-dd");

  try {
    // 1. Fetch Latest Data from Supabase
    const marketData = fetchLatestDataFromSupabase();

    // 2. Fetch Latest Trading Signals generated by Python (e.g. Z-Score, FX limits)
    const strategySignals = fetchLatestSignalsFromSupabase();

    // 2.5 Extract Trends
    const getMacro = (ticker, isPrevious = false) => {
      if (!marketData || !marketData.macro) return 0;
      const items = marketData.macro.filter(m => m.ticker === ticker);
      if (items.length === 0) return 0;
      if (isPrevious && items.length > 1) return parseFloat(items[Math.min(items.length - 1, 5)].value);
      return parseFloat(items[0].value);
    };

    const fxRate = getMacro('DEXKOUS');
    const fxPrev = getMacro('DEXKOUS', true) || fxRate;
    const vix = getMacro('VIXCLS');
    const vixPrev = getMacro('VIXCLS', true) || vix;

    // Netliq
    const fedAssetsRaw = getMacro('WALCL');
    const tgaRaw = getMacro('WTREGEN');
    const rrp = getMacro('RRPONTSYD');

    const fedAssetsPrevRaw = getMacro('WALCL', true);
    const tgaPrevRaw = getMacro('WTREGEN', true);
    const rrpPrev = getMacro('RRPONTSYD', true);

    const netLiq = (fedAssetsRaw ? fedAssetsRaw / 1000 : 0) - (tgaRaw ? tgaRaw / 1000 : 0) - rrp;
    const netLiqPrev = (fedAssetsPrevRaw ? fedAssetsPrevRaw / 1000 : 0) - (tgaPrevRaw ? tgaPrevRaw / 1000 : 0) - rrpPrev;

    const trends = {
      fx_change: (fxRate - fxPrev).toFixed(1),
      vix_change: (vix - vixPrev).toFixed(2),
      net_liquidity_change_billions: (netLiq - netLiqPrev).toFixed(0)
    };

    // 3. Generate Deep Insight using Gemini AI 
    const aiInsightText = getGeminiDeepInsight(marketData, strategySignals, todayKR, trends);

    // 4. Render and Send Email
    const emailHtml = renderFullReportEmail(marketData, strategySignals, aiInsightText, todayKR);

    // Extract a headline or strategy mode from the signals mapping
    const stratMsg = (strategySignals.find(s => s.indicator === 'FX_HEDGE_RATIO') || {}).metadata?.strategy_msg || "Normal Strategy";
    const subject = `[AI Quant Report] ${todayKR} : ${stratMsg}`;

    sendEmailReport(subject, emailHtml);

    console.log("--- ✅ [Reporter] Finished successfully ---");
  } catch (e) {
    console.error("❌ Reporter Error: " + e.message);
  }
}

// ==========================================
// [SUPABASE FETCHING]
// ==========================================
function fetchLatestDataFromSupabase() {
  const headers = {
    "apikey": CONFIG.SB_KEY,
    "Authorization": "Bearer " + CONFIG.SB_KEY
  };

  let marketData = {
    assets: [],
    macro: [],
    news: []
  };

  try {
    // Fetch Assets
    const resAsset = UrlFetchApp.fetch(`${CONFIG.SB_URL}/rest/v1/asset_metrics?order=date.desc&limit=50`, { headers: headers, muteHttpExceptions: true });
    marketData.assets = JSON.parse(resAsset.getContentText());

    // Fetch Macro - Increased limit to 100 to catch all indicators which may update on different days
    const resMacro = UrlFetchApp.fetch(`${CONFIG.SB_URL}/rest/v1/macro_indicators?order=date.desc&limit=100`, { headers: headers, muteHttpExceptions: true });
    marketData.macro = JSON.parse(resMacro.getContentText());

    // Fetch News Sentiment
    const resNews = UrlFetchApp.fetch(`${CONFIG.SB_URL}/rest/v1/news_sentiment?order=date.desc&limit=20`, { headers: headers, muteHttpExceptions: true });
    marketData.news = JSON.parse(resNews.getContentText());
  } catch (e) {
    console.error("Failed to fetch market data:", e);
  }

  return marketData;
}

function fetchLatestSignalsFromSupabase() {
  const headers = {
    "apikey": CONFIG.SB_KEY,
    "Authorization": "Bearer " + CONFIG.SB_KEY
  };

  try {
    // We changed the Python engine to save signals in macro_indicators with ticker='FX_HEDGE_RATIO'
    const resFX = UrlFetchApp.fetch(`${CONFIG.SB_URL}/rest/v1/macro_indicators?ticker=eq.FX_HEDGE_RATIO&order=date.desc&limit=1`, { headers: headers, muteHttpExceptions: true });
    let fxData = JSON.parse(resFX.getContentText());

    // RAG context is now pushed to the news_sentiment table under symbol='RAG_CONTEXT'
    const resRAG = UrlFetchApp.fetch(`${CONFIG.SB_URL}/rest/v1/news_sentiment?symbol=eq.RAG_CONTEXT&order=date.desc&limit=1`, { headers: headers, muteHttpExceptions: true });
    let ragData = JSON.parse(resRAG.getContentText());

    let signals = [];

    if (fxData && fxData.length > 0) {
      signals.push({
        date: fxData[0].date,
        indicator: "FX_HEDGE_RATIO",
        value: fxData[0].value,
        metadata: {
          fx_rate: "N/A (Check Raw Data)",
          z_score: "N/A",
          strategy_msg: `Today's FX Hedge Ratio Target: ${fxData[0].value * 100}%`
        }
      });
    }

    if (ragData && ragData.length > 0) {
      signals.push({
        date: ragData[0].date,
        indicator: "RAG_HISTORICAL_MATCH",
        value: ragData[0].buzz_volume, // number of matches
        metadata: { rag_context: ragData[0].title || "과거 데이터베이스 매칭 결과가 없습니다." }
      });
    }

    return signals;
  } catch (e) {
    console.error("Failed to fetch signals:", e);
  }

  return [];
}

// ==========================================
// [GEMINI AI INTEGRATION]
// ==========================================
function getGeminiDeepInsight(market, signals, dateStr, trends) {
  // Extract RAG Context from the signals
  const ragSignal = signals.find(s => s.indicator === 'RAG_HISTORICAL_MATCH');
  const ragContext = (ragSignal && ragSignal.metadata && ragSignal.metadata.rag_context) 
                      ? ragSignal.metadata.rag_context 
                      : "최근 유사한 과거 사례 기록이 없습니다.";

  const marketContext = {
    date: dateStr,
    recent_news: (market.news || []).slice(0, 5).map(n => n.title), // [NEW] Top 5 News Headlines
    macro_indicators: market.macro,           // 기존 거시 지표
    asset_prices: market.assets,              // 추가: 주가 지수, 금, 비트코인 등 자산 데이터 전달
    recent_trends: trends, 
    python_engine_signals: signals,
    ai_memory_retrieval_rag: ragContext       // [NEW] 벡터 DB 검색을 통한 과거 유사 사례 (RAG)
  };

  const prompt = `
    당신의 이름은 'Quant Master'이며, 거시경제 지표와 금융 데이터를 해석해 주는 친절하고 전문적인 AI 퀀트 비서입니다.
    아래는 시스템이 수집한 오늘자 거시경제 지표, 최신 금융 뉴스, 자산 가격 데이터, 그리고 과거 가장 유사했던 시장 상황에 대한 데이터(ai_memory_retrieval_rag)입니다.
    독자가 현재 시장의 맥락을 이해하고, 각 지표들이 현재 장세에서 어떤 의미를 가지는지 쉽게 파악할 수 있도록 브리핑 리포트를 작성하세요.

    [SYSTEM_DATA]
    ${JSON.stringify(marketContext, null, 2)}

    [작성 규칙]
    1. 데이터 코드명(예: WTREGEN, VIXCLS)은 리포트에 절대 노출하지 마세요. (대신 'TGA(미 재무부 일반계정)', 'VIX(미국 S&P 500 변동성 지수)' 등으로 표기)
    2. 'ai_memory_retrieval_rag'라는 시스템 변수명이나 'RAG'라는 기계적인 단어를 절대 쓰지 마세요. 대신 "과거 OOOO년 O월의 유사한 데이터 패턴을 참고해보면~" 처럼 자연스럽고 전문적으로 녹여내세요.
    3. 종목 추천이나 구체적인 자산 매수/매도(비중 조절) 리딩은 하지 마세요. 대신 현재 수치가 '시장 심리나 유동성에 어떤 영향을 미치고 있는지' 해석해 주는 데 집중하세요.
    4. 문체는 단호하고 전문적인 보고서 톤(~함, ~임, ~결과임)을 유지하며, 글이 너무 늘어지지 않게 핵심만 짚어주세요.

    [분석의 핵심 (RAG 데이터 및 자산 간 상관관계 100% 활용)]
    - 🔥 **과거와의 입체적 비교 분석**: 현재 지표(VIX 18 등)가 겉보기에 평온해 보이더라도, 시스템이 굳이 최악의 폭락장(예: 2020년 3월, 2022년 6월)을 가장 유사한 과거로 매칭(RAG)했다면 그 이유를 파헤쳐야 합니다. 단순 수치 비교를 넘어, 직전 과거 대비 현재 방어막(유동성 등)이 얼마나 더 얇은지 저울질하세요.
    - 🔥 **자산 및 지표 간 상관관계(Correlation & Divergence) 분석**: 단순히 개별 지표를 나열하는 것은 하수입니다. "현재 달러가 약세인데, 비트코인과 금이 동반 상승(양의 상관관계)하고 있다" 혹은 "국채 금리가 오르는데 기술주가 안 빠진다(디커플링/발산 현상)" 같은 **시장 내 톱니바퀴들의 연결성**을 날카롭게 짚어내야 합니다. 자산군들의 움직임이 정상적인 베타(Beta)를 따르고 있는지, 아니면 뭔가 이상 조짐(Divergence)이 있는지를 반드시 짚어주세요.

    [출력 포맷 (반드시 아래 마크다운 양식을 사용할 것)]
    ## 데일리 퀀트 브리핑 (${dateStr})

    ---
    [핵심 요약]
    (현재 시스템이 감지한 유동성/변동성의 핵심 흐름과, 과거 유사 사례(RAG) 및 주요 뉴스를 종합한 오늘의 가장 중요한 관전 포인트를 3줄 이내로 압축)

    ---
    A. 자산 간 상관관계 및 디커플링 진단 (Correlation & Divergence)
    (뉴스 센티멘트 보도(recent_news)와 더불어 달러, 환율, 금리, 주식, 금 등 주요 자산들이 현재 **어떻게 서로 얽혀서 움직이고 있는지** 1~2문단으로 날카롭게 분석. 뉴스의 호재/악재가 실제 거시 자산 흐름과 동조화되는지 디커플링되는지 짚어줄 것)

    ---
    B. 리스크 점검 (과거 유사 사례 기반 비교점)
    (시스템이 찾아낸 과거 유사 국면(RAG)의 특징을 언급하고, 현재 수치와 직접 저울질하여 현재 시점의 숨겨진 리스크 크기나 기회를 '비교 분석'할 것. 과거보다 무엇은 낫고 무엇은 최악인지 명확히 서술)

    ---
    C. 주요 거시 지표 모니터링 가이드
    (현재 장세에서 주의 깊게 봐야 할 3~4개의 핵심 거시 지표(유동성, VIX, 스프레드 등)를 선정하여, "현재 이 지표가 과거 위기 당시와 비교해 OOO 수치인데, 이는 시장에 ~한 의미를 가진다" 형식으로 해설)
  `;

  try {
    var url = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=' + CONFIG.GEMINI_API_KEY;
    var payload = { "contents": [{ "parts": [{ "text": prompt }] }] };
    var res = UrlFetchApp.fetch(url, {
      method: "POST", contentType: "application/json", payload: JSON.stringify(payload), muteHttpExceptions: true
    });
    return JSON.parse(res.getContentText()).candidates[0].content.parts[0].text;
  } catch (e) { return "AI 분석에 실패했습니다. (API 오류)"; }
}

// ==========================================
// [EMAIL RENDERING]
// ==========================================
function renderFullReportEmail(market, signals, aiReport, todayStr) {
  const fxSignal = signals.find(s => s.indicator === 'FX_HEDGE_RATIO') || {};
  const meta = fxSignal.metadata || {};

  // Extract macro values securely
  const getMacro = (ticker, isPrevious = false) => {
    if (!market || !market.macro) return 0;
    const items = market.macro.filter(m => m.ticker === ticker);
    if (items.length === 0) return 0;
    // IF isPrevious is true, try to get a value from about 5-7 days ago (or the oldest available in the limit if < 5)
    if (isPrevious && items.length > 1) {
      // items are sorted date desc. Find one that is at least a few days old, or just pick the last one.
      return parseFloat(items[Math.min(items.length - 1, 5)].value);
    }
    return parseFloat(items[0].value);
  };

  const getAssetPrice = (symbol) => {
    if (!market || !market.assets) return 0;
    const items = market.assets.filter(a => a.symbol === symbol);
    if (items.length === 0) return 0;
    return parseFloat(items[0].close_price);
  };
  
  const krRate = getMacro('KR_BASE_RATE') || 0;
  const usRate = getMacro('FEDFUNDS') || getMacro('DGS2') || 0;
  const rateDiff = (krRate - usRate).toFixed(2);

  const cpi = getMacro('CPALTT01USM657N') || 0;
  const pce = getMacro('PCEPI') || 0;

  // Asset Price Changes for AI Context
  const getAssetTrend = (symbol) => {
    if (!market || !market.assets) return { price: 0, changePct: 0 };
    const items = market.assets.filter(a => a.symbol === symbol);
    if (items.length < 2) return { price: items.length === 1 ? parseFloat(items[0].close_price) : 0, changePct: 0 };
    
    const curr = parseFloat(items[0].close_price);
    // Find the closest previous trading day (usually index 1 if sorted by date desc)
    const prev = parseFloat(items[1].close_price);
    const changePct = prev > 0 ? ((curr - prev) / prev) * 100 : 0;
    return { price: curr, changePct: changePct.toFixed(2) };
  };

  const btc = getAssetTrend('BTC-USD');
  const gold = getAssetTrend('GC=F');
  const sp500 = getAssetTrend('^GSPC');
  const kospi = getAssetTrend('KOSPI200');

  // Push these exact trends into the marketContext so AI doesn't hallucinate
  if (marketContext.recent_trends) {
    marketContext.recent_trends.asset_daily_changes = {
      "BTC (Bitcoin)": `${btc.changePct}%`,
      "Gold": `${gold.changePct}%`,
      "S&P 500": `${sp500.changePct}%`,
      "KOSPI 200": `${kospi.changePct}%`
    };
  }

  // 주가/자산 가격 (이메일 표기용)
  const btcPrice = btc.price;
  const goldPrice = gold.price;
  const sp500Price = sp500.price;

  // 환율
  const fxRate = getMacro('DEXKOUS') || 0;
  const fxPrev = getMacro('DEXKOUS', true) || fxRate;
  const fxChange = fxRate - fxPrev;
  const fxArrow = fxChange > 0 ? "🔺" : (fxChange < 0 ? "🔻" : "-");

  const vix = getMacro('VIXCLS') || 0;
  const vixPrev = getMacro('VIXCLS', true) || vix;
  const vixChange = vix - vixPrev;
  const vixArrow = vixChange > 0 ? "🔺" : (vixChange < 0 ? "🔻" : "-");

  const tgaRaw = getMacro('WTREGEN');
  const tga = tgaRaw ? (tgaRaw / 1000) : 0;
  const rrp = getMacro('RRPONTSYD');
  const fedAssetsRaw = getMacro('WALCL');
  const fedAssets = fedAssetsRaw ? Math.round(fedAssetsRaw / 1000) : 0;

  let netLiq = 0;
  if (fedAssets > 0) {
    netLiq = fedAssets - tga - rrp;
  }

  // Previous Liquidity
  const tgaPrevRaw = getMacro('WTREGEN', true);
  const tgaPrev = tgaPrevRaw ? (tgaPrevRaw / 1000) : 0;
  const rrpPrev = getMacro('RRPONTSYD', true);
  const fedAssetsPrevRaw = getMacro('WALCL', true);
  const fedAssetsPrev = fedAssetsPrevRaw ? Math.round(fedAssetsPrevRaw / 1000) : 0;
  let netLiqPrev = 0; if (fedAssetsPrev > 0) netLiqPrev = fedAssetsPrev - tgaPrev - rrpPrev;
  const liqChange = netLiq - netLiqPrev;
  const liqArrow = liqChange > 0 ? "🔺" : (liqChange < 0 ? "🔻" : "-");

  const highYield = getMacro('BAMLH0A0HYM2EY') || getMacro('BAMLH0A0HYM2') || 0;
  const finStress = getMacro('STLFSI3') || 0;
  const ted = getMacro('TEDRATE') || 0;

  const stratMode = meta.strategy_msg || (vix > 25 ? "DEFENSE (Crisis)" : "NORMAL (Accumulate)");
  const liquidityStatus = (netLiq > 0 && netLiq < 6000) ? "위험(유동성흡수)" : "양호(유동성공급)";

  const dashboardHtml = `
    <div style="background:#003366; color:white; padding:15px; font-family:sans-serif;">
      <h2 style="margin:0; font-size:20px;">Daily Market Briefing</h2>
      <p style="margin:5px 0 0; font-size:12px; color:#cfd8dc;">Data Sources: ECOS, FRED, Supabase, Python Engine</p>
    </div>
    
    <div style="padding:15px; background:#fff; border:1px solid #ddd; margin-top:15px; border-left: 5px solid #d32f2f;">
      <h3 style="margin:0 0 5px 0; color:#424242; font-size:14px;">CURRENT STRATEGY</h3>
      <div style="font-size:22px; font-weight:800; color:#b71c1c;">${stratMode}</div>
      <div style="color:#616161; font-size:15px; margin-top:5px; font-weight:bold;">유동성 상태: ${liquidityStatus}</div>
    </div>

    <table style="width:100%; border-collapse: collapse; font-size: 13px; border:1px solid #e0e0e0; margin-top:10px; text-align:center;">
      <tr style="background:#f8f9fa;">
        <td colspan="6" style="padding:12px; border-bottom:2px solid #003366; font-weight:bold; color:#003366; text-align:left;">
          주요 자산 동향 (Prices)
        </td>
      </tr>
      <tr>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">비트코인 (BTC)</td>
        <td style="padding:10px; border:1px solid #eee; font-weight:bold; color:#f57f17;">$${btcPrice > 0 ? btcPrice.toLocaleString() : '-'}</td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">금 (Gold)</td>
        <td style="padding:10px; border:1px solid #eee; font-weight:bold; color:#fbc02d;">$${goldPrice > 0 ? goldPrice.toLocaleString() : '-'}</td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">S&P 500</td>
        <td style="padding:10px; border:1px solid #eee; font-weight:bold; color:#1565c0;">${sp500Price > 0 ? sp500Price.toLocaleString() : '-'}</td>
      </tr>
      <tr style="background:#f8f9fa;">
        <td colspan="6" style="padding:12px; border-bottom:2px solid #003366; border-top:2px solid #003366; font-weight:bold; color:#003366; text-align:left;">
          핵심 경제 지표 대시보드 (최근 대비 변동)
        </td>
      </tr>
      <tr>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">한국 기준금리</td>
        <td style="padding:10px; border:1px solid #eee; font-weight:bold;">${krRate}%</td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">미국 기준금리</td>
        <td style="padding:10px; border:1px solid #eee; font-weight:bold;">${usRate}%</td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">한미 금리차</td>
        <td style="padding:10px; border:1px solid #eee; font-weight:bold; color:${rateDiff < 0 ? 'red' : 'blue'};">${rateDiff}%p</td>
      </tr>
      <tr>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">환율 (USD/KRW)</td>
        <td style="padding:10px; border:1px solid #eee; font-weight:bold;">${fxRate}원 <span style="font-size:11px;color:#888;">${fxArrow}${Math.abs(fxChange).toFixed(1)}</span></td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">순유동성</td>
        <td style="padding:10px; border:1px solid #eee; font-weight:bold;">$${Math.round(netLiq)} B <span style="font-size:11px;color:#888;">${liqArrow}${Math.round(Math.abs(liqChange))}</span></td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">VIX (공포)</td>
        <td style="padding:10px; border:1px solid #eee; font-weight:bold; color:${vix > 20 ? 'red' : 'black'};">${vix} <span style="font-size:11px;color:#888;">${vixArrow}${Math.abs(vixChange).toFixed(2)}</span></td>
      </tr>
      <tr>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">TGA (정부잔고)</td>
        <td style="padding:10px; border:1px solid #eee;">$${Math.round(tga)} B</td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">RRP (역레포)</td>
        <td style="padding:10px; border:1px solid #eee;">$${Math.round(rrp)} B</td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">Fed 총자산</td>
        <td style="padding:10px; border:1px solid #eee;">$${fedAssets} B</td>
      </tr>
      <tr>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">하이일드 실효금리</td>
        <td style="padding:10px; border:1px solid #eee;">${highYield}%</td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">미국 CPI (인플레)</td>
        <td style="padding:10px; border:1px solid #eee;">${cpi.toFixed(2)}%</td>
        <td style="padding:10px; border:1px solid #eee; background:#fafafa; text-align:left;">PCE 물가지수</td>
        <td style="padding:10px; border:1px solid #eee;">${pce.toFixed(2)}</td>
      </tr>
    </table>
  `;

  const formattedInsight = formatAiText(aiReport);

  return `
    <!DOCTYPE html>
    <html>
    <body style="font-family:'Apple SD Gothic Neo', sans-serif; background-color:#f4f6f8; padding:20px;">
      <div style="max-width: 800px; margin:0 auto; background:#ffffff; border:1px solid #dce0e4; border-radius: 8px; overflow:hidden;">
        
        ${dashboardHtml}

        <div style="padding:25px;">
          <div style="background:#e3f2fd; border:1px solid #bbdefb; padding:15px; border-radius:4px; margin-top:10px;">
            <div style="font-size:13px; color:#1565c0; font-weight:bold;">Quant Engine Status</div>
            <div style="font-size:14px; color:#333; margin-top:5px;">
              Python 파이프라인에서 도출된 최신 지표가 분석에 반영되었습니다.
            </div>
          </div>

          <h3 style="font-size:18px; color:#003366; border-bottom:2px solid #eee; padding-bottom:10px; margin-top:30px;">
            AI Analyst Insight
          </h3>
          <div style="font-size:15px; line-height:1.7; color:#333;">
            ${formattedInsight}
          </div>
        </div>
      </div>
    </body>
    </html>
  `;
}

// ==========================================
// [UTILITIES]
// ==========================================
function formatAiText(text) {
  if (!text) return "";
  let html = text;

  // 1. 구분선 처리
  html = html.replace(/^---$/gm, '<hr style="border:0; border-top:1px dashed #ccc; margin: 30px 0;">');

  // 2. 핵심 요약 / 섹션 헤더 처리 (A. 팩트체크 등)
  html = html.replace(/^\[핵심 요약\]/gm, '<div style="background:#fff3e0; border-left:4px solid #f57c00; padding:6px 10px; font-weight:800; color:#e65100; margin: 25px 0 10px 0; font-size:15px; display:inline-block; border-radius:2px;">📌 핵심 요약</div>');
  html = html.replace(/^([A-C]\. .*)/gm, '<h3 style="margin: 35px 0 12px 0; color: #003366; font-size: 17px; padding-bottom: 8px; border-bottom: 2px solid #e0e0e0;">$1</h3>');

  // 3. 형광펜 및 강조
  html = html.replace(/^### ?(.*)/gm, '<h4 style="margin: 25px 0 10px 0; color: #003366; font-size: 16px;">$1</h4>');
  html = html.replace(/^\*\* ?(.*)\*\*$/gm, '<h4 style="margin: 25px 0 10px 0; color: #003366; font-size: 16px;">$1</h4>');
  html = html.replace(/\[\[(.*?)\]\]/g, '<span style="background-color: #ffebee; color: #c62828; font-weight: bold; padding: 2px 4px; border-radius: 3px;">$1</span>');
  html = html.replace(/\(\((.*?)\)\)/g, '<span style="background-color: #e3f2fd; color: #1565c0; font-weight: bold; padding: 2px 4px; border-radius: 3px;">$1</span>');
  html = html.replace(/\*\*(.*?)\*\*/g, '<b style="color:#222; font-size:15.5px;">$1</b>');

  // 4. 리스트 아이템 여백 넓히기 (단락 구분 극대화)
  html = html.replace(/^\* (.*)/gm, '<div style="margin-top:15px; margin-bottom:15px; color:#444; line-height:1.7;">• $1</div>');
  html = html.replace(/^- (.*)/gm, '<div style="margin-top:15px; margin-bottom:15px; color:#444; line-height:1.7;">🔹 $1</div>');

  return html.replace(/\n/g, '<br>');
}

function sendEmailReport(subject, htmlBody) {
  MailApp.sendEmail({ to: CONFIG.EMAIL_RECIPIENT, subject: subject, htmlBody: htmlBody });
}
